package sun.java2d.pipe;
/*
* Copyright (c) 1999, Oracle and/or its affiliates. All rights reserved.
* DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
*
* This code is free software; you can redistribute it and/or modify it
* under the terms of the GNU General Public License version 2 only, as
* published by the Free Software Foundation.  Oracle designates this
* particular file as subject to the "Classpath" exception as provided
* by Oracle in the LICENSE file that accompanied this code.
*
* This code is distributed in the hope that it will be useful, but WITHOUT
* ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
* FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
* version 2 for more details (a copy is included in the LICENSE file that
* accompanied this code).
*
* You should have received a copy of the GNU General Public License version
* 2 along with this work; if not, write to the Free Software Foundation,
* Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
*
* Please contact Oracle, 500 Oracle Parkway, Redwood Shores, CA 94065 USA
* or visit www.oracle.com if you need additional information or have any
* questions.
*/
extern class RegionClipSpanIterator implements sun.java2d.pipe.SpanIterator
{
	/*
	* Creates an instance that filters the spans generated by
	* spanIter through the region described by rgn.
	*/
	@:overload @:public public function new(rgn : sun.java2d.pipe.Region, spanIter : sun.java2d.pipe.SpanIterator) : Void;
	
	/*
	* Gets the bbox of the available path segments, clipped to the
	* Region.
	*/
	@:overload @:public public function getPathBox(pathbox : java.NativeArray<Int>) : Void;
	
	/*
	* Intersects the path box with the given bbox.
	* Returned spans are clipped to this region, or discarded
	* altogether if they lie outside it.
	*/
	@:overload @:public public function intersectClipBox(lox : Int, loy : Int, hix : Int, hiy : Int) : Void;
	
	/*
	* Fetches the next span that needs to be operated on.
	* If the return value is false then there are no more spans.
	*/
	@:overload @:public public function nextSpan(resultbox : java.NativeArray<Int>) : Bool;
	
	/**
	* This method tells the iterator that it may skip all spans
	* whose Y range is completely above the indicated Y coordinate.
	*/
	@:overload @:public public function skipDownTo(y : Int) : Void;
	
	/**
	* This method returns a native pointer to a function block that
	* can be used by a native method to perform the same iteration
	* cycle that the above methods provide while avoiding upcalls to
	* the Java object.
	* The definition of the structure whose pointer is returned by
	* this method is defined in:
	* <pre>
	*     src/share/native/sun/java2d/pipe/SpanIterator.h
	* </pre>
	*/
	@:overload @:public public function getNativeIterator() : haxe.Int64;
	
	/*
	* Cleans out all internal data structures.
	*/
	@:overload @:protected private function finalize() : Void;
	
	
}
