package org.omg.PortableInterceptor.ORBInitInfoPackage;
/**
* org/omg/PortableInterceptor/ORBInitInfoPackage/DuplicateName.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../../src/share/classes/org/omg/PortableInterceptor/Interceptors.idl
* Thursday, February 21, 2013 9:14:02 AM UTC
*/
extern class DuplicateName extends org.omg.CORBA.UserException
{
	/** 
	* The name for which there was already an interceptor registered.
	*/
	public var name : String;
	
	@:overload public function new() : Void;
	
	@:overload public function new(_name : String) : Void;
	
	@:overload public function new($reason : String, _name : String) : Void;
	
	
}
