package org.omg.PortableInterceptor.ORBInitInfoPackage;
/**
* org/omg/PortableInterceptor/ORBInitInfoPackage/InvalidName.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../../src/share/classes/org/omg/PortableInterceptor/Interceptors.idl
* Thursday, February 21, 2013 9:14:02 AM UTC
*/
extern class InvalidName extends org.omg.CORBA.UserException
{
	@:overload public function new() : Void;
	
	@:overload public function new($reason : String) : Void;
	
	
}
