package com.sun.corba.se.PortableActivationIDL.RepositoryPackage;
/**
* com/sun/corba/se/PortableActivationIDL/RepositoryPackage/ServerDef.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../../src/share/classes/com/sun/corba/se/PortableActivationIDL/activation.idl
* Thursday, February 21, 2013 9:14:13 AM UTC
*/
extern class ServerDef implements org.omg.CORBA.portable.IDLEntity
{
	@:public public var applicationName : String;
	
	@:public public var serverName : String;
	
	@:public public var serverClassPath : String;
	
	@:public public var serverArgs : String;
	
	@:public public var serverVmArgs : String;
	
	@:public public var isInstalled : Bool;
	
	@:overload @:public public function new() : Void;
	
	@:overload @:public public function new(_applicationName : String, _serverName : String, _serverClassPath : String, _serverArgs : String, _serverVmArgs : String, _isInstalled : Bool) : Void;
	
	
}
