package org.omg.CORBA;
/**
* org/omg/CORBA/ParameterMode.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../../src/share/classes/org/omg/PortableInterceptor/CORBAX.idl
* Thursday, February 21, 2013 9:14:02 AM UTC
*/
/**
* Enumeration of parameter modes for Parameter.  Possible vaues:
* <ul>
*   <li>PARAM_IN - Represents an "in" parameter.</li>
*   <li>PARAM_OUT - Represents an "out" parameter.</li>
*   <li>PARAM_INOUT - Represents an "inout" parameter.</li>
* </ul>
*/
extern class ParameterMode implements org.omg.CORBA.portable.IDLEntity
{
	@:public @:static @:final public static var _PARAM_IN(default, null) : Int;
	
	@:public @:static @:final public static var PARAM_IN(default, null) : org.omg.CORBA.ParameterMode;
	
	@:public @:static @:final public static var _PARAM_OUT(default, null) : Int;
	
	@:public @:static @:final public static var PARAM_OUT(default, null) : org.omg.CORBA.ParameterMode;
	
	@:public @:static @:final public static var _PARAM_INOUT(default, null) : Int;
	
	@:public @:static @:final public static var PARAM_INOUT(default, null) : org.omg.CORBA.ParameterMode;
	
	@:overload @:public public function value() : Int;
	
	@:overload @:public @:static public static function from_int(value : Int) : org.omg.CORBA.ParameterMode;
	
	@:overload @:protected private function new(value : Int) : Void;
	
	
}
