package org.omg.CORBA;
/**
* org/omg/CORBA/PolicyErrorCodeHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../../src/share/classes/org/omg/PortableInterceptor/CORBAX.idl
* Thursday, February 21, 2013 9:14:02 AM UTC
*/
/** 
* Encapsulates a reason a Policy may be invalid.
*
* @see PolicyError
*/
extern class PolicyErrorCodeHelper
{
	@:overload public static function insert(a : org.omg.CORBA.Any, that : java.StdTypes.Int16) : Void;
	
	@:overload public static function extract(a : org.omg.CORBA.Any) : java.StdTypes.Int16;
	
	@:overload @:synchronized public static function type() : org.omg.CORBA.TypeCode;
	
	@:overload public static function id() : String;
	
	@:overload public static function read(istream : org.omg.CORBA.portable.InputStream) : java.StdTypes.Int16;
	
	@:overload public static function write(ostream : org.omg.CORBA.portable.OutputStream, value : java.StdTypes.Int16) : Void;
	
	
}
