package org.omg.CORBA;
/**
* org/omg/CORBA/PolicyErrorHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../../src/share/classes/org/omg/PortableInterceptor/CORBAX.idl
* Thursday, February 21, 2013 9:14:02 AM UTC
*/
/**
* Thrown to indicate problems with parameter values passed to the
* <code>ORB.create_policy</code> operation.  
*/
extern class PolicyErrorHelper
{
	@:overload @:public @:static public static function insert(a : org.omg.CORBA.Any, that : org.omg.CORBA.PolicyError) : Void;
	
	@:overload @:public @:static public static function extract(a : org.omg.CORBA.Any) : org.omg.CORBA.PolicyError;
	
	@:overload @:synchronized @:public @:static public static function type() : org.omg.CORBA.TypeCode;
	
	@:overload @:public @:static public static function id() : String;
	
	@:overload @:public @:static public static function read(istream : org.omg.CORBA.portable.InputStream) : org.omg.CORBA.PolicyError;
	
	@:overload @:public @:static public static function write(ostream : org.omg.CORBA.portable.OutputStream, value : org.omg.CORBA.PolicyError) : Void;
	
	
}
