package org.omg.CosNaming;
/**
* org/omg/CosNaming/BindingIteratorOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../../src/share/classes/org/omg/CosNaming/nameservice.idl
* Thursday, February 21, 2013 9:14:02 AM UTC
*/
/**
* The BindingIterator interface allows a client to iterate through
* the bindings using the next_one or next_n operations.
* 
* The bindings iterator is obtained by using the <tt>list</tt>
* method on the <tt>NamingContext</tt>. 
* @see org.omg.CosNaming.NamingContext#list
*/
extern interface BindingIteratorOperations
{
	/**
	* This operation returns the next binding. If there are no more
	* bindings, false is returned.
	* 
	* @param b the returned binding
	*/
	@:overload @:public public function next_one(b : org.omg.CosNaming.BindingHolder) : Bool;
	
	/**
	* This operation returns at most the requested number of bindings.
	* 
	* @param how_many the maximum number of bindings tro return <p>
	* 
	* @param bl the returned bindings
	*/
	@:overload @:public public function next_n(how_many : Int, bl : org.omg.CosNaming.BindingListHolder) : Bool;
	
	/**
	* This operation destroys the iterator.
	*/
	@:overload @:public public function destroy() : Void;
	
	
}
