package org.omg.CosNaming;
/**
* org/omg/CosNaming/NamingContextExtPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../../src/share/classes/org/omg/CosNaming/nameservice.idl
* Thursday, February 21, 2013 9:14:02 AM UTC
*/
/** 
* <code>NamingContextExt</code> is the extension of <code>NamingContext</code>
* which
* contains a set of name bindings in which each name is unique and is
* part of Interoperable Naming Service.
* Different names can be bound to an object in the same or different
* contexts at the same time. Using <tt>NamingContextExt</tt>, you can use
* URL-based names to bind and resolve. <p>
* 
* See <a href="http://www.omg.org/technology/documents/formal/naming_service.htm">
* CORBA COS 
* Naming Specification.</a>
*/
extern class NamingContextExtPOA extends org.omg.PortableServer.Servant implements org.omg.CosNaming.NamingContextExtOperations implements org.omg.CORBA.portable.InvokeHandler
{
	@:overload public function _invoke($method : String, _in : org.omg.CORBA.portable.InputStream, $rh : org.omg.CORBA.portable.ResponseHandler) : org.omg.CORBA.portable.OutputStream;
	
	@:overload override public function _all_interfaces(poa : org.omg.PortableServer.POA, objectId : java.NativeArray<java.StdTypes.Int8>) : java.NativeArray<String>;
	
	@:overload public function _this() : org.omg.CosNaming.NamingContextExt;
	
	@:overload public function _this(orb : org.omg.CORBA.ORB) : org.omg.CosNaming.NamingContextExt;
	
	
}
