package com.sun.jmx.snmp.IPAcl;
/*
* Copyright (c) 1997, 2003, Oracle and/or its affiliates. All rights reserved.
* DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
*
* This code is free software; you can redistribute it and/or modify it
* under the terms of the GNU General Public License version 2 only, as
* published by the Free Software Foundation.  Oracle designates this
* particular file as subject to the "Classpath" exception as provided
* by Oracle in the LICENSE file that accompanied this code.
*
* This code is distributed in the hope that it will be useful, but WITHOUT
* ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
* FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
* version 2 for more details (a copy is included in the LICENSE file that
* accompanied this code).
*
* You should have received a copy of the GNU General Public License version
* 2 along with this work; if not, write to the Free Software Foundation,
* Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
*
* Please contact Oracle, 500 Oracle Parkway, Redwood Shores, CA 94065 USA
* or visit www.oracle.com if you need additional information or have any
* questions.
*/
/* Generated By:JJTree&JavaCC: Do not edit this line. ParserTokenManager.java */
@:internal extern class ParserTokenManager implements com.sun.jmx.snmp.IPAcl.ParserConstants.ParserConstants
{
	public static var jjstrLiteralImages(default, null) : java.NativeArray<java.lang.String.String>;
	
	public static var lexStateNames(default, null) : java.NativeArray<java.lang.String.String>;
	
	private var curChar : java.StdTypes.Char16;
	
	@:overload public function new(stream : com.sun.jmx.snmp.IPAcl.ASCII_CharStream.ASCII_CharStream) : Void;
	
	@:overload public function new(stream : com.sun.jmx.snmp.IPAcl.ASCII_CharStream.ASCII_CharStream, lexState : Int) : Void;
	
	@:overload public function ReInit(stream : com.sun.jmx.snmp.IPAcl.ASCII_CharStream.ASCII_CharStream) : Void;
	
	@:overload public function ReInit(stream : com.sun.jmx.snmp.IPAcl.ASCII_CharStream.ASCII_CharStream, lexState : Int) : Void;
	
	@:overload public function SwitchTo(lexState : Int) : Void;
	
	@:overload @:final public function getNextToken() : com.sun.jmx.snmp.IPAcl.Token.Token;
	
	
}
