package com.sun.jmx.snmp.IPAcl;
/*
* Copyright (c) 1997, 2003, Oracle and/or its affiliates. All rights reserved.
* DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
*
* This code is free software; you can redistribute it and/or modify it
* under the terms of the GNU General Public License version 2 only, as
* published by the Free Software Foundation.  Oracle designates this
* particular file as subject to the "Classpath" exception as provided
* by Oracle in the LICENSE file that accompanied this code.
*
* This code is distributed in the hope that it will be useful, but WITHOUT
* ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
* FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
* version 2 for more details (a copy is included in the LICENSE file that
* accompanied this code).
*
* You should have received a copy of the GNU General Public License version
* 2 along with this work; if not, write to the Free Software Foundation,
* Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
*
* Please contact Oracle, 500 Oracle Parkway, Redwood Shores, CA 94065 USA
* or visit www.oracle.com if you need additional information or have any
* questions.
*/
/* Generated By:JJTree: Do not edit this line. ParserTreeConstants.java */
@:internal extern interface ParserTreeConstants
{
	public var JJTSECURITYDEFS : Int;
	
	public var JJTACLBLOCK : Int;
	
	public var JJTACLITEM : Int;
	
	public var JJTCOMMUNITIES : Int;
	
	public var JJTCOMMUNITY : Int;
	
	public var JJTACCESS : Int;
	
	public var JJTMANAGERS : Int;
	
	public var JJTHOST : Int;
	
	public var JJTHOSTNAME : Int;
	
	public var JJTIPADDRESS : Int;
	
	public var JJTIPV6ADDRESS : Int;
	
	public var JJTIPMASK : Int;
	
	public var JJTNETMASK : Int;
	
	public var JJTNETMASKV6 : Int;
	
	public var JJTTRAPBLOCK : Int;
	
	public var JJTTRAPITEM : Int;
	
	public var JJTTRAPCOMMUNITY : Int;
	
	public var JJTTRAPINTERESTEDHOST : Int;
	
	public var JJTHOSTTRAP : Int;
	
	public var JJTENTERPRISE : Int;
	
	public var JJTTRAPNUM : Int;
	
	public var JJTINFORMBLOCK : Int;
	
	public var JJTINFORMITEM : Int;
	
	public var JJTINFORMCOMMUNITY : Int;
	
	public var JJTINFORMINTERESTEDHOST : Int;
	
	public var JJTHOSTINFORM : Int;
	
	public var jjtNodeName : java.NativeArray<java.lang.String.String>;
	
	
}
