package com.sun.jmx.snmp.IPAcl;
/*
* Copyright (c) 1997, 2003, Oracle and/or its affiliates. All rights reserved.
* DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
*
* This code is free software; you can redistribute it and/or modify it
* under the terms of the GNU General Public License version 2 only, as
* published by the Free Software Foundation.  Oracle designates this
* particular file as subject to the "Classpath" exception as provided
* by Oracle in the LICENSE file that accompanied this code.
*
* This code is distributed in the hope that it will be useful, but WITHOUT
* ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
* FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
* version 2 for more details (a copy is included in the LICENSE file that
* accompanied this code).
*
* You should have received a copy of the GNU General Public License version
* 2 along with this work; if not, write to the Free Software Foundation,
* Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
*
* Please contact Oracle, 500 Oracle Parkway, Redwood Shores, CA 94065 USA
* or visit www.oracle.com if you need additional information or have any
* questions.
*/
/* Generated By:JJTree&JavaCC: Do not edit this line. ParserConstants.java */
@:internal extern interface ParserConstants
{
	public var EOF : Int;
	
	public var ACCESS : Int;
	
	public var ACL : Int;
	
	public var ASSIGN : Int;
	
	public var COMMUNITIES : Int;
	
	public var ENTERPRISE : Int;
	
	public var HOSTS : Int;
	
	public var LBRACE : Int;
	
	public var MANAGERS : Int;
	
	public var RANGE : Int;
	
	public var RBRACE : Int;
	
	public var RO : Int;
	
	public var RW : Int;
	
	public var TRAP : Int;
	
	public var INFORM : Int;
	
	public var TRAPCOMMUNITY : Int;
	
	public var INFORMCOMMUNITY : Int;
	
	public var TRAPNUM : Int;
	
	public var INTEGER_LITERAL : Int;
	
	public var DECIMAL_LITERAL : Int;
	
	public var HEX_LITERAL : Int;
	
	public var OCTAL_LITERAL : Int;
	
	public var V6_ADDRESS : Int;
	
	public var H : Int;
	
	public var D : Int;
	
	public var IDENTIFIER : Int;
	
	public var LETTER : Int;
	
	public var SEPARATOR : Int;
	
	public var DIGIT : Int;
	
	public var CSTRING : Int;
	
	public var COMMA : Int;
	
	public var DOT : Int;
	
	public var MARK : Int;
	
	public var MASK : Int;
	
	public var DEFAULT : Int;
	
	public var tokenImage : java.NativeArray<java.lang.String.String>;
	
	
}
