package com.sun.corba.se.PortableActivationIDL;
/**
* com/sun/corba/se/PortableActivationIDL/Locator.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../../src/share/classes/com/sun/corba/se/PortableActivationIDL/activation.idl
* Thursday, February 21, 2013 9:14:13 AM UTC
*/
extern interface Locator extends com.sun.corba.se.PortableActivationIDL.LocatorOperations extends org.omg.CORBA.Object extends org.omg.CORBA.portable.IDLEntity
{
	
}
