package com.sun.corba.se.PortableActivationIDL;
/**
* com/sun/corba/se/PortableActivationIDL/NoSuchEndPointHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../../src/share/classes/com/sun/corba/se/PortableActivationIDL/activation.idl
* Thursday, February 21, 2013 9:14:13 AM UTC
*/
extern class NoSuchEndPointHelper
{
	@:overload public static function insert(a : org.omg.CORBA.Any, that : com.sun.corba.se.PortableActivationIDL.NoSuchEndPoint) : Void;
	
	@:overload public static function extract(a : org.omg.CORBA.Any) : com.sun.corba.se.PortableActivationIDL.NoSuchEndPoint;
	
	@:overload @:synchronized public static function type() : org.omg.CORBA.TypeCode;
	
	@:overload public static function id() : String;
	
	@:overload public static function read(istream : org.omg.CORBA.portable.InputStream) : com.sun.corba.se.PortableActivationIDL.NoSuchEndPoint;
	
	@:overload public static function write(ostream : org.omg.CORBA.portable.OutputStream, value : com.sun.corba.se.PortableActivationIDL.NoSuchEndPoint) : Void;
	
	
}
