package com.sun.corba.se.PortableActivationIDL;
/**
* com/sun/corba/se/PortableActivationIDL/ORBProxyOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../../src/share/classes/com/sun/corba/se/PortableActivationIDL/activation.idl
* Thursday, February 21, 2013 9:14:13 AM UTC
*/
/** ORB callback interface, passed to Activator in registerORB method.
*/
extern interface ORBProxyOperations
{
	/** Method used to cause ORB to activate the named adapter, if possible.
		* This will cause the named POA to register itself with the activator as
		* a side effect.  This should always happen before this call can complete.
		* This method returns true if adapter activation succeeded, otherwise it
		* returns false.
		*/
	@:overload public function activate_adapter(name : java.NativeArray<String>) : Bool;
	
	
}
