package com.sun.corba.se.PortableActivationIDL;
/**
* com/sun/corba/se/PortableActivationIDL/ServerManager.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../../src/share/classes/com/sun/corba/se/PortableActivationIDL/activation.idl
* Thursday, February 21, 2013 9:14:13 AM UTC
*/
/** Interface used to combine the Activator and Locator when both are
* implemented together in the same process, as is currently the case
* for our implementation.
*/
extern interface ServerManager extends com.sun.corba.se.PortableActivationIDL.ServerManagerOperations extends com.sun.corba.se.PortableActivationIDL.Activator extends com.sun.corba.se.PortableActivationIDL.Locator
{
	
}
