package com.sun.corba.se.PortableActivationIDL;
/**
* com/sun/corba/se/PortableActivationIDL/TCPPortHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../../src/share/classes/com/sun/corba/se/PortableActivationIDL/activation.idl
* Thursday, February 21, 2013 9:14:13 AM UTC
*/
/** Type of TCP port number, used in structures that describe 
* transport endpoints.  The valid range is actually 0-65535, but
* we use a long here to avoid signed/unsigned conversion headaches
* in Java.
*/
extern class TCPPortHelper
{
	@:overload @:public @:static public static function insert(a : org.omg.CORBA.Any, that : Int) : Void;
	
	@:overload @:public @:static public static function extract(a : org.omg.CORBA.Any) : Int;
	
	@:overload @:synchronized @:public @:static public static function type() : org.omg.CORBA.TypeCode;
	
	@:overload @:public @:static public static function id() : String;
	
	@:overload @:public @:static public static function read(istream : org.omg.CORBA.portable.InputStream) : Int;
	
	@:overload @:public @:static public static function write(ostream : org.omg.CORBA.portable.OutputStream, value : Int) : Void;
	
	
}
