package sun.management.snmp.jvmmib;
/*
* Copyright (c) 2003, 2004, Oracle and/or its affiliates. All rights reserved.
* DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
*
* This code is free software; you can redistribute it and/or modify it
* under the terms of the GNU General Public License version 2 only, as
* published by the Free Software Foundation.  Oracle designates this
* particular file as subject to the "Classpath" exception as provided
* by Oracle in the LICENSE file that accompanied this code.
*
* This code is distributed in the hope that it will be useful, but WITHOUT
* ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
* FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
* version 2 for more details (a copy is included in the LICENSE file that
* accompanied this code).
*
* You should have received a copy of the GNU General Public License version
* 2 along with this work; if not, write to the Free Software Foundation,
* Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
*
* Please contact Oracle, 500 Oracle Parkway, Redwood Shores, CA 94065 USA
* or visit www.oracle.com if you need additional information or have any
* questions.
*/
////
//// Generated by mibgen version 5.0 (06/02/03) when compiling JVM-MANAGEMENT-MIB in standard metadata mode.
////
//// jmx imports
////
/**
* This interface is used for representing the remote management interface for the "JvmThreadInstanceEntry" MBean.
*/
extern interface JvmThreadInstanceEntryMBean
{
	/**
	* Getter for the "JvmThreadInstName" variable.
	*/
	@:overload public function getJvmThreadInstName() : java.lang.String.String;
	
	/**
	* Getter for the "JvmThreadInstCpuTimeNs" variable.
	*/
	@:overload public function getJvmThreadInstCpuTimeNs() : java.lang.Long.Long;
	
	/**
	* Getter for the "JvmThreadInstWaitTimeMs" variable.
	*/
	@:overload public function getJvmThreadInstWaitTimeMs() : java.lang.Long.Long;
	
	/**
	* Getter for the "JvmThreadInstWaitCount" variable.
	*/
	@:overload public function getJvmThreadInstWaitCount() : java.lang.Long.Long;
	
	/**
	* Getter for the "JvmThreadInstBlockTimeMs" variable.
	*/
	@:overload public function getJvmThreadInstBlockTimeMs() : java.lang.Long.Long;
	
	/**
	* Getter for the "JvmThreadInstBlockCount" variable.
	*/
	@:overload public function getJvmThreadInstBlockCount() : java.lang.Long.Long;
	
	/**
	* Getter for the "JvmThreadInstState" variable.
	*/
	@:overload public function getJvmThreadInstState() : java.NativeArray<java.lang.Byte.Byte>;
	
	/**
	* Getter for the "JvmThreadInstLockOwnerPtr" variable.
	*/
	@:overload public function getJvmThreadInstLockOwnerPtr() : java.lang.String.String;
	
	/**
	* Getter for the "JvmThreadInstId" variable.
	*/
	@:overload public function getJvmThreadInstId() : java.lang.Long.Long;
	
	/**
	* Getter for the "JvmThreadInstLockName" variable.
	*/
	@:overload public function getJvmThreadInstLockName() : java.lang.String.String;
	
	/**
	* Getter for the "JvmThreadInstIndex" variable.
	*/
	@:overload public function getJvmThreadInstIndex() : java.NativeArray<java.lang.Byte.Byte>;
	
	
}
