package com.sun.tools.example.debug.expr;
/*
* Copyright (c) 1999, 2004, Oracle and/or its affiliates. All rights reserved.
* DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
*
* This code is free software; you can redistribute it and/or modify it
* under the terms of the GNU General Public License version 2 only, as
* published by the Free Software Foundation.  Oracle designates this
* particular file as subject to the "Classpath" exception as provided
* by Oracle in the LICENSE file that accompanied this code.
*
* This code is distributed in the hope that it will be useful, but WITHOUT
* ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
* FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
* version 2 for more details (a copy is included in the LICENSE file that
* accompanied this code).
*
* You should have received a copy of the GNU General Public License version
* 2 along with this work; if not, write to the Free Software Foundation,
* Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
*
* Please contact Oracle, 500 Oracle Parkway, Redwood Shores, CA 94065 USA
* or visit www.oracle.com if you need additional information or have any
* questions.
*/
/*
* This source code is provided to illustrate the usage of a given feature
* or technique and has been deliberately simplified. Additional steps
* required for a production-quality application, such as security checks,
* input validation and proper error handling, might not be present in
* this sample code.
*/
/* Generated By:JavaCC: Do not edit this line. ASCII_UCodeESC_CharStream.java Version 0.7pre6 */
/**
* An implementation of interface CharStream, where the stream is assumed to
* contain only ASCII characters (with java-like unicode escape processing).
*/
extern class ASCII_UCodeESC_CharStream
{
	public static var staticFlag(default, null) : Bool;
	
	public var bufpos : Int;
	
	@:overload @:final public function BeginToken() : java.StdTypes.Char16;
	
	@:overload @:final public function readChar() : java.StdTypes.Char16;
	
	/**
	* @deprecated
	* @see #getEndColumn
	*/
	@:overload @:final public function getColumn() : Int;
	
	/**
	* @deprecated
	* @see #getEndLine
	*/
	@:overload @:final public function getLine() : Int;
	
	@:overload @:final public function getEndColumn() : Int;
	
	@:overload @:final public function getEndLine() : Int;
	
	@:overload @:final public function getBeginColumn() : Int;
	
	@:overload @:final public function getBeginLine() : Int;
	
	@:overload @:final public function backup(amount : Int) : Void;
	
	@:overload public function new(dstream : java.io.InputStream, startline : Int, startcolumn : Int, buffersize : Int) : Void;
	
	@:overload public function new(dstream : java.io.InputStream, startline : Int, startcolumn : Int) : Void;
	
	@:overload public function ReInit(dstream : java.io.InputStream, startline : Int, startcolumn : Int, buffersize : Int) : Void;
	
	@:overload public function ReInit(dstream : java.io.InputStream, startline : Int, startcolumn : Int) : Void;
	
	@:overload @:final public function GetImage() : String;
	
	@:overload @:final public function GetSuffix(len : Int) : java.NativeArray<java.StdTypes.Char16>;
	
	@:overload public function Done() : Void;
	
	/**
	* Method to adjust line and column numbers for the start of a token.<BR>
	*/
	@:overload public function adjustBeginLineColumn(newLine : Int, newCol : Int) : Void;
	
	
}
