package sun.awt.X11;
//// This file is an automatically generated file, please do not edit this file, modify the WrapperGenerator.java file instead !
extern class ColorData extends sun.awt.X11.XWrapperBase
{
	@:overload public static function getSize() : Int;
	
	@:overload override public function getDataSize() : Int;
	
	@:overload override public function getPData() : haxe.Int64;
	
	@:overload public function new(addr : haxe.Int64) : Void;
	
	@:overload public function new() : Void;
	
	@:overload public function dispose() : Void;
	
	@:overload public function get_awt_Colors(index : Int) : sun.awt.X11.ColorEntry;
	
	@:overload public function get_awt_Colors() : haxe.Int64;
	
	@:overload public function set_awt_Colors(v : haxe.Int64) : Void;
	
	@:overload public function get_awt_numICMcolors() : Int;
	
	@:overload public function set_awt_numICMcolors(v : Int) : Void;
	
	@:overload public function get_awt_icmLUT(index : Int) : Int;
	
	@:overload public function get_awt_icmLUT() : haxe.Int64;
	
	@:overload public function set_awt_icmLUT(v : haxe.Int64) : Void;
	
	@:overload public function get_awt_icmLUT2Colors(index : Int) : java.StdTypes.Int8;
	
	@:overload public function get_awt_icmLUT2Colors() : haxe.Int64;
	
	@:overload public function set_awt_icmLUT2Colors(v : haxe.Int64) : Void;
	
	@:overload public function get_img_grays(index : Int) : java.StdTypes.Int8;
	
	@:overload public function get_img_grays() : haxe.Int64;
	
	@:overload public function set_img_grays(v : haxe.Int64) : Void;
	
	@:overload public function get_img_clr_tbl(index : Int) : java.StdTypes.Int8;
	
	@:overload public function get_img_clr_tbl() : haxe.Int64;
	
	@:overload public function set_img_clr_tbl(v : haxe.Int64) : Void;
	
	@:overload public function get_img_oda_red(index : Int) : java.StdTypes.Int8;
	
	@:overload public function get_img_oda_red() : haxe.Int64;
	
	@:overload public function set_img_oda_red(v : haxe.Int64) : Void;
	
	@:overload public function get_img_oda_green(index : Int) : java.StdTypes.Int8;
	
	@:overload public function get_img_oda_green() : haxe.Int64;
	
	@:overload public function set_img_oda_green(v : haxe.Int64) : Void;
	
	@:overload public function get_img_oda_blue(index : Int) : java.StdTypes.Int8;
	
	@:overload public function get_img_oda_blue() : haxe.Int64;
	
	@:overload public function set_img_oda_blue(v : haxe.Int64) : Void;
	
	@:overload public function get_pGrayInverseLutData(index : Int) : Int;
	
	@:overload public function get_pGrayInverseLutData() : haxe.Int64;
	
	@:overload public function set_pGrayInverseLutData(v : haxe.Int64) : Void;
	
	@:overload public function get_screendata() : Int;
	
	@:overload public function set_screendata(v : Int) : Void;
	
	
}
