package sun.awt.X11;
//// This file is an automatically generated file, please do not edit this file, modify the WrapperGenerator.java file instead !
extern class Depth extends sun.awt.X11.XWrapperBase
{
	@:overload @:public @:static public static function getSize() : Int;
	
	@:overload @:public override public function getDataSize() : Int;
	
	@:overload @:public override public function getPData() : haxe.Int64;
	
	@:overload @:public public function new(addr : haxe.Int64) : Void;
	
	@:overload @:public public function new() : Void;
	
	@:overload @:public public function dispose() : Void;
	
	@:overload @:public public function get_depth() : Int;
	
	@:overload @:public public function set_depth(v : Int) : Void;
	
	@:overload @:public public function get_nvisuals() : Int;
	
	@:overload @:public public function set_nvisuals(v : Int) : Void;
	
	@:overload @:public public function get_visuals(index : Int) : sun.awt.X11.Visual;
	
	@:overload @:public public function get_visuals() : haxe.Int64;
	
	@:overload @:public public function set_visuals(v : haxe.Int64) : Void;
	
	
}
