package sun.awt.X11;
//// This file is an automatically generated file, please do not edit this file, modify the WrapperGenerator.java file instead !
extern class Visual extends sun.awt.X11.XWrapperBase
{
	@:overload @:public @:static public static function getSize() : Int;
	
	@:overload @:public override public function getDataSize() : Int;
	
	@:overload @:public override public function getPData() : haxe.Int64;
	
	@:overload @:public public function new(addr : haxe.Int64) : Void;
	
	@:overload @:public public function new() : Void;
	
	@:overload @:public public function dispose() : Void;
	
	@:overload @:public public function get_ext_data(index : Int) : sun.awt.X11.XExtData;
	
	@:overload @:public public function get_ext_data() : haxe.Int64;
	
	@:overload @:public public function set_ext_data(v : haxe.Int64) : Void;
	
	@:overload @:public public function get_visualid() : haxe.Int64;
	
	@:overload @:public public function set_visualid(v : haxe.Int64) : Void;
	
	@:overload @:public public function get_class() : Int;
	
	@:overload @:public public function set_class(v : Int) : Void;
	
	@:overload @:public public function get_red_mask() : haxe.Int64;
	
	@:overload @:public public function set_red_mask(v : haxe.Int64) : Void;
	
	@:overload @:public public function get_green_mask() : haxe.Int64;
	
	@:overload @:public public function set_green_mask(v : haxe.Int64) : Void;
	
	@:overload @:public public function get_blue_mask() : haxe.Int64;
	
	@:overload @:public public function set_blue_mask(v : haxe.Int64) : Void;
	
	@:overload @:public public function get_bits_per_rgb() : Int;
	
	@:overload @:public public function set_bits_per_rgb(v : Int) : Void;
	
	@:overload @:public public function get_map_entries() : Int;
	
	@:overload @:public public function set_map_entries(v : Int) : Void;
	
	
}
