package sun.awt.X11;
//// This file is an automatically generated file, please do not edit this file, modify the WrapperGenerator.java file instead !
extern class XArc extends sun.awt.X11.XWrapperBase
{
	@:overload @:public @:static public static function getSize() : Int;
	
	@:overload @:public override public function getDataSize() : Int;
	
	@:overload @:public override public function getPData() : haxe.Int64;
	
	@:overload @:public public function new(addr : haxe.Int64) : Void;
	
	@:overload @:public public function new() : Void;
	
	@:overload @:public public function dispose() : Void;
	
	@:overload @:public public function get_x() : java.StdTypes.Int16;
	
	@:overload @:public public function set_x(v : java.StdTypes.Int16) : Void;
	
	@:overload @:public public function get_y() : java.StdTypes.Int16;
	
	@:overload @:public public function set_y(v : java.StdTypes.Int16) : Void;
	
	@:overload @:public public function get_width() : java.StdTypes.Int16;
	
	@:overload @:public public function set_width(v : java.StdTypes.Int16) : Void;
	
	@:overload @:public public function get_height() : java.StdTypes.Int16;
	
	@:overload @:public public function set_height(v : java.StdTypes.Int16) : Void;
	
	@:overload @:public public function get_angle1() : java.StdTypes.Int16;
	
	@:overload @:public public function set_angle1(v : java.StdTypes.Int16) : Void;
	
	@:overload @:public public function get_angle2() : java.StdTypes.Int16;
	
	@:overload @:public public function set_angle2(v : java.StdTypes.Int16) : Void;
	
	
}
