package sun.awt.X11;
//// This file is an automatically generated file, please do not edit this file, modify the WrapperGenerator.java file instead !
extern class XCharStruct extends sun.awt.X11.XWrapperBase
{
	@:overload public static function getSize() : Int;
	
	@:overload public function getDataSize() : Int;
	
	@:overload public function getPData() : haxe.Int64;
	
	@:overload public function new(addr : haxe.Int64) : Void;
	
	@:overload public function new() : Void;
	
	@:overload public function dispose() : Void;
	
	@:overload public function get_lbearing() : java.StdTypes.Int16;
	
	@:overload public function set_lbearing(v : java.StdTypes.Int16) : Void;
	
	@:overload public function get_rbearing() : java.StdTypes.Int16;
	
	@:overload public function set_rbearing(v : java.StdTypes.Int16) : Void;
	
	@:overload public function get_width() : java.StdTypes.Int16;
	
	@:overload public function set_width(v : java.StdTypes.Int16) : Void;
	
	@:overload public function get_ascent() : java.StdTypes.Int16;
	
	@:overload public function set_ascent(v : java.StdTypes.Int16) : Void;
	
	@:overload public function get_descent() : java.StdTypes.Int16;
	
	@:overload public function set_descent(v : java.StdTypes.Int16) : Void;
	
	@:overload public function get_attributes() : java.StdTypes.Int16;
	
	@:overload public function set_attributes(v : java.StdTypes.Int16) : Void;
	
	
}
