package sun.awt.X11;
//// This file is an automatically generated file, please do not edit this file, modify the WrapperGenerator.java file instead !
extern class XChar2b extends sun.awt.X11.XWrapperBase
{
	@:overload @:public @:static public static function getSize() : Int;
	
	@:overload @:public override public function getDataSize() : Int;
	
	@:overload @:public override public function getPData() : haxe.Int64;
	
	@:overload @:public public function new(addr : haxe.Int64) : Void;
	
	@:overload @:public public function new() : Void;
	
	@:overload @:public public function dispose() : Void;
	
	@:overload @:public public function get_byte1() : java.StdTypes.Int8;
	
	@:overload @:public public function set_byte1(v : java.StdTypes.Int8) : Void;
	
	@:overload @:public public function get_byte2() : java.StdTypes.Int8;
	
	@:overload @:public public function set_byte2(v : java.StdTypes.Int8) : Void;
	
	
}
