package sun.awt.X11;
//// This file is an automatically generated file, please do not edit this file, modify the WrapperGenerator.java file instead !
extern class XClassHint extends sun.awt.X11.XWrapperBase
{
	@:overload @:public @:static public static function getSize() : Int;
	
	@:overload @:public override public function getDataSize() : Int;
	
	@:overload @:public override public function getPData() : haxe.Int64;
	
	@:overload @:public public function new(addr : haxe.Int64) : Void;
	
	@:overload @:public public function new() : Void;
	
	@:overload @:public public function dispose() : Void;
	
	@:overload @:public public function get_res_name(index : Int) : haxe.Int64;
	
	@:overload @:public public function get_res_name() : haxe.Int64;
	
	@:overload @:public public function set_res_name(v : haxe.Int64) : Void;
	
	@:overload @:public public function get_res_class(index : Int) : haxe.Int64;
	
	@:overload @:public public function get_res_class() : haxe.Int64;
	
	@:overload @:public public function set_res_class(v : haxe.Int64) : Void;
	
	
}
