package sun.awt.X11;
//// This file is an automatically generated file, please do not edit this file, modify the WrapperGenerator.java file instead !
extern class XComposeStatus extends sun.awt.X11.XWrapperBase
{
	@:overload public static function getSize() : Int;
	
	@:overload override public function getDataSize() : Int;
	
	@:overload override public function getPData() : haxe.Int64;
	
	@:overload public function new(addr : haxe.Int64) : Void;
	
	@:overload public function new() : Void;
	
	@:overload public function dispose() : Void;
	
	@:overload public function get_compose_ptr(index : Int) : haxe.Int64;
	
	@:overload public function get_compose_ptr() : haxe.Int64;
	
	@:overload public function set_compose_ptr(v : haxe.Int64) : Void;
	
	@:overload public function get_chars_matched() : Int;
	
	@:overload public function set_chars_matched(v : Int) : Void;
	
	
}
