package sun.awt.X11;
//// This file is an automatically generated file, please do not edit this file, modify the WrapperGenerator.java file instead !
extern class XErrorEvent extends sun.awt.X11.XWrapperBase
{
	@:overload public static function getSize() : Int;
	
	@:overload override public function getDataSize() : Int;
	
	@:overload override public function getPData() : haxe.Int64;
	
	@:overload public function new(addr : haxe.Int64) : Void;
	
	@:overload public function new() : Void;
	
	@:overload public function dispose() : Void;
	
	@:overload public function get_type() : Int;
	
	@:overload public function set_type(v : Int) : Void;
	
	@:overload public function get_display() : haxe.Int64;
	
	@:overload public function set_display(v : haxe.Int64) : Void;
	
	@:overload public function get_resourceid() : haxe.Int64;
	
	@:overload public function set_resourceid(v : haxe.Int64) : Void;
	
	@:overload public function get_serial() : haxe.Int64;
	
	@:overload public function set_serial(v : haxe.Int64) : Void;
	
	@:overload public function get_error_code() : java.StdTypes.Int8;
	
	@:overload public function set_error_code(v : java.StdTypes.Int8) : Void;
	
	@:overload public function get_request_code() : java.StdTypes.Int8;
	
	@:overload public function set_request_code(v : java.StdTypes.Int8) : Void;
	
	@:overload public function get_minor_code() : java.StdTypes.Int8;
	
	@:overload public function set_minor_code(v : java.StdTypes.Int8) : Void;
	
	
}
