package sun.awt.X11;
//// This file is an automatically generated file, please do not edit this file, modify the WrapperGenerator.java file instead !
extern class XExposeEvent extends sun.awt.X11.XWrapperBase
{
	@:overload public static function getSize() : Int;
	
	@:overload override public function getDataSize() : Int;
	
	@:overload override public function getPData() : haxe.Int64;
	
	@:overload public function new(addr : haxe.Int64) : Void;
	
	@:overload public function new() : Void;
	
	@:overload public function dispose() : Void;
	
	@:overload public function get_type() : Int;
	
	@:overload public function set_type(v : Int) : Void;
	
	@:overload public function get_serial() : haxe.Int64;
	
	@:overload public function set_serial(v : haxe.Int64) : Void;
	
	@:overload public function get_send_event() : Bool;
	
	@:overload public function set_send_event(v : Bool) : Void;
	
	@:overload public function get_display() : haxe.Int64;
	
	@:overload public function set_display(v : haxe.Int64) : Void;
	
	@:overload public function get_window() : haxe.Int64;
	
	@:overload public function set_window(v : haxe.Int64) : Void;
	
	@:overload public function get_x() : Int;
	
	@:overload public function set_x(v : Int) : Void;
	
	@:overload public function get_y() : Int;
	
	@:overload public function set_y(v : Int) : Void;
	
	@:overload public function get_width() : Int;
	
	@:overload public function set_width(v : Int) : Void;
	
	@:overload public function get_height() : Int;
	
	@:overload public function set_height(v : Int) : Void;
	
	@:overload public function get_count() : Int;
	
	@:overload public function set_count(v : Int) : Void;
	
	
}
