package sun.awt.X11;
//// This file is an automatically generated file, please do not edit this file, modify the WrapperGenerator.java file instead !
extern class XFontStruct extends sun.awt.X11.XWrapperBase
{
	@:overload public static function getSize() : Int;
	
	@:overload override public function getDataSize() : Int;
	
	@:overload override public function getPData() : haxe.Int64;
	
	@:overload public function new(addr : haxe.Int64) : Void;
	
	@:overload public function new() : Void;
	
	@:overload public function dispose() : Void;
	
	@:overload public function get_ext_data(index : Int) : sun.awt.X11.XExtData;
	
	@:overload public function get_ext_data() : haxe.Int64;
	
	@:overload public function set_ext_data(v : haxe.Int64) : Void;
	
	@:overload public function get_fid() : haxe.Int64;
	
	@:overload public function set_fid(v : haxe.Int64) : Void;
	
	@:overload public function get_direction() : Int;
	
	@:overload public function set_direction(v : Int) : Void;
	
	@:overload public function get_min_char_or_byte2() : Int;
	
	@:overload public function set_min_char_or_byte2(v : Int) : Void;
	
	@:overload public function get_max_char_or_byte2() : Int;
	
	@:overload public function set_max_char_or_byte2(v : Int) : Void;
	
	@:overload public function get_min_byte1() : Int;
	
	@:overload public function set_min_byte1(v : Int) : Void;
	
	@:overload public function get_max_byte1() : Int;
	
	@:overload public function set_max_byte1(v : Int) : Void;
	
	@:overload public function get_all_chars_exist() : Bool;
	
	@:overload public function set_all_chars_exist(v : Bool) : Void;
	
	@:overload public function get_n_properties() : Int;
	
	@:overload public function set_n_properties(v : Int) : Void;
	
	@:overload public function get_properties(index : Int) : sun.awt.X11.XFontProp;
	
	@:overload public function get_properties() : haxe.Int64;
	
	@:overload public function set_properties(v : haxe.Int64) : Void;
	
	@:overload public function get_min_bounds() : sun.awt.X11.XCharStruct;
	
	@:overload public function get_max_bounds() : sun.awt.X11.XCharStruct;
	
	@:overload public function get_per_char(index : Int) : sun.awt.X11.XCharStruct;
	
	@:overload public function get_per_char() : haxe.Int64;
	
	@:overload public function set_per_char(v : haxe.Int64) : Void;
	
	@:overload public function get_ascent() : Int;
	
	@:overload public function set_ascent(v : Int) : Void;
	
	@:overload public function get_descent() : Int;
	
	@:overload public function set_descent(v : Int) : Void;
	
	
}
