package sun.awt.X11;
//// This file is an automatically generated file, please do not edit this file, modify the WrapperGenerator.java file instead !
extern class XGCValues extends sun.awt.X11.XWrapperBase
{
	@:overload @:public @:static public static function getSize() : Int;
	
	@:overload @:public override public function getDataSize() : Int;
	
	@:overload @:public override public function getPData() : haxe.Int64;
	
	@:overload @:public public function new(addr : haxe.Int64) : Void;
	
	@:overload @:public public function new() : Void;
	
	@:overload @:public public function dispose() : Void;
	
	@:overload @:public public function get_function() : Int;
	
	@:overload @:public public function set_function(v : Int) : Void;
	
	@:overload @:public public function get_plane_mask() : haxe.Int64;
	
	@:overload @:public public function set_plane_mask(v : haxe.Int64) : Void;
	
	@:overload @:public public function get_foreground() : haxe.Int64;
	
	@:overload @:public public function set_foreground(v : haxe.Int64) : Void;
	
	@:overload @:public public function get_background() : haxe.Int64;
	
	@:overload @:public public function set_background(v : haxe.Int64) : Void;
	
	@:overload @:public public function get_line_width() : Int;
	
	@:overload @:public public function set_line_width(v : Int) : Void;
	
	@:overload @:public public function get_line_style() : Int;
	
	@:overload @:public public function set_line_style(v : Int) : Void;
	
	@:overload @:public public function get_cap_style() : Int;
	
	@:overload @:public public function set_cap_style(v : Int) : Void;
	
	@:overload @:public public function get_join_style() : Int;
	
	@:overload @:public public function set_join_style(v : Int) : Void;
	
	@:overload @:public public function get_fill_style() : Int;
	
	@:overload @:public public function set_fill_style(v : Int) : Void;
	
	@:overload @:public public function get_fill_rule() : Int;
	
	@:overload @:public public function set_fill_rule(v : Int) : Void;
	
	@:overload @:public public function get_arc_mode() : Int;
	
	@:overload @:public public function set_arc_mode(v : Int) : Void;
	
	@:overload @:public public function get_tile() : haxe.Int64;
	
	@:overload @:public public function set_tile(v : haxe.Int64) : Void;
	
	@:overload @:public public function get_stipple() : haxe.Int64;
	
	@:overload @:public public function set_stipple(v : haxe.Int64) : Void;
	
	@:overload @:public public function get_ts_x_origin() : Int;
	
	@:overload @:public public function set_ts_x_origin(v : Int) : Void;
	
	@:overload @:public public function get_ts_y_origin() : Int;
	
	@:overload @:public public function set_ts_y_origin(v : Int) : Void;
	
	@:overload @:public public function get_font() : haxe.Int64;
	
	@:overload @:public public function set_font(v : haxe.Int64) : Void;
	
	@:overload @:public public function get_subwindow_mode() : Int;
	
	@:overload @:public public function set_subwindow_mode(v : Int) : Void;
	
	@:overload @:public public function get_graphics_exposures() : Bool;
	
	@:overload @:public public function set_graphics_exposures(v : Bool) : Void;
	
	@:overload @:public public function get_clip_x_origin() : Int;
	
	@:overload @:public public function set_clip_x_origin(v : Int) : Void;
	
	@:overload @:public public function get_clip_y_origin() : Int;
	
	@:overload @:public public function set_clip_y_origin(v : Int) : Void;
	
	@:overload @:public public function get_clip_mask() : haxe.Int64;
	
	@:overload @:public public function set_clip_mask(v : haxe.Int64) : Void;
	
	@:overload @:public public function get_dash_offset() : Int;
	
	@:overload @:public public function set_dash_offset(v : Int) : Void;
	
	@:overload @:public public function get_dashes() : java.StdTypes.Int8;
	
	@:overload @:public public function set_dashes(v : java.StdTypes.Int8) : Void;
	
	
}
