package sun.awt.X11;
//// This file is an automatically generated file, please do not edit this file, modify the WrapperGenerator.java file instead !
extern class XIMHotKeyTriggers extends sun.awt.X11.XWrapperBase
{
	@:overload @:public @:static public static function getSize() : Int;
	
	@:overload @:public override public function getDataSize() : Int;
	
	@:overload @:public override public function getPData() : haxe.Int64;
	
	@:overload @:public public function new(addr : haxe.Int64) : Void;
	
	@:overload @:public public function new() : Void;
	
	@:overload @:public public function dispose() : Void;
	
	@:overload @:public public function get_num_hot_key() : Int;
	
	@:overload @:public public function set_num_hot_key(v : Int) : Void;
	
	@:overload @:public public function get_key(index : Int) : sun.awt.X11.XIMHotKeyTrigger;
	
	@:overload @:public public function get_key() : haxe.Int64;
	
	@:overload @:public public function set_key(v : haxe.Int64) : Void;
	
	
}
