package sun.awt.X11;
//// This file is an automatically generated file, please do not edit this file, modify the WrapperGenerator.java file instead !
extern class XIMPreeditDrawCallbackStruct extends sun.awt.X11.XWrapperBase
{
	@:overload @:public @:static public static function getSize() : Int;
	
	@:overload @:public override public function getDataSize() : Int;
	
	@:overload @:public override public function getPData() : haxe.Int64;
	
	@:overload @:public public function new(addr : haxe.Int64) : Void;
	
	@:overload @:public public function new() : Void;
	
	@:overload @:public public function dispose() : Void;
	
	@:overload @:public public function get_caret() : Int;
	
	@:overload @:public public function set_caret(v : Int) : Void;
	
	@:overload @:public public function get_chg_first() : Int;
	
	@:overload @:public public function set_chg_first(v : Int) : Void;
	
	@:overload @:public public function get_chg_length() : Int;
	
	@:overload @:public public function set_chg_length(v : Int) : Void;
	
	@:overload @:public public function get_text(index : Int) : sun.awt.X11.XIMText;
	
	@:overload @:public public function get_text() : haxe.Int64;
	
	@:overload @:public public function set_text(v : haxe.Int64) : Void;
	
	
}
