package sun.awt.X11;
//// This file is an automatically generated file, please do not edit this file, modify the WrapperGenerator.java file instead !
extern class XIMStatusDrawCallbackStruct extends sun.awt.X11.XWrapperBase
{
	@:overload public static function getSize() : Int;
	
	@:overload public function getDataSize() : Int;
	
	@:overload public function getPData() : haxe.Int64;
	
	@:overload public function new(addr : haxe.Int64) : Void;
	
	@:overload public function new() : Void;
	
	@:overload public function dispose() : Void;
	
	@:overload public function get_type() : Int;
	
	@:overload public function set_type(v : Int) : Void;
	
	@:overload public function get_data() : haxe.Int64;
	
	@:overload public function set_data(v : haxe.Int64) : Void;
	
	
}
