package sun.awt.X11;
//// This file is an automatically generated file, please do not edit this file, modify the WrapperGenerator.java file instead !
extern class XIMValuesList extends sun.awt.X11.XWrapperBase
{
	@:overload @:public @:static public static function getSize() : Int;
	
	@:overload @:public override public function getDataSize() : Int;
	
	@:overload @:public override public function getPData() : haxe.Int64;
	
	@:overload @:public public function new(addr : haxe.Int64) : Void;
	
	@:overload @:public public function new() : Void;
	
	@:overload @:public public function dispose() : Void;
	
	@:overload @:public public function get_count_values() : java.StdTypes.Int16;
	
	@:overload @:public public function set_count_values(v : java.StdTypes.Int16) : Void;
	
	@:overload @:public public function get_supported_values(index : Int) : haxe.Int64;
	
	@:overload @:public public function get_supported_values() : haxe.Int64;
	
	@:overload @:public public function set_supported_values(v : haxe.Int64) : Void;
	
	
}
