package sun.awt.X11;
//// This file is an automatically generated file, please do not edit this file, modify the WrapperGenerator.java file instead !
extern class XkbAccessXNotifyEvent extends sun.awt.X11.XWrapperBase
{
	@:overload public static function getSize() : Int;
	
	@:overload public function getDataSize() : Int;
	
	@:overload public function getPData() : haxe.Int64;
	
	@:overload public function new(addr : haxe.Int64) : Void;
	
	@:overload public function new() : Void;
	
	@:overload public function dispose() : Void;
	
	@:overload public function get_type() : Int;
	
	@:overload public function set_type(v : Int) : Void;
	
	@:overload public function get_serial() : haxe.Int64;
	
	@:overload public function set_serial(v : haxe.Int64) : Void;
	
	@:overload public function get_send_event() : Bool;
	
	@:overload public function set_send_event(v : Bool) : Void;
	
	@:overload public function get_display() : haxe.Int64;
	
	@:overload public function set_display(v : haxe.Int64) : Void;
	
	@:overload public function get_time() : haxe.Int64;
	
	@:overload public function set_time(v : haxe.Int64) : Void;
	
	@:overload public function get_xkb_type() : Int;
	
	@:overload public function set_xkb_type(v : Int) : Void;
	
	@:overload public function get_device() : Int;
	
	@:overload public function set_device(v : Int) : Void;
	
	@:overload public function get_detail() : Int;
	
	@:overload public function set_detail(v : Int) : Void;
	
	@:overload public function get_keycode() : Int;
	
	@:overload public function set_keycode(v : Int) : Void;
	
	@:overload public function get_sk_delay() : Int;
	
	@:overload public function set_sk_delay(v : Int) : Void;
	
	@:overload public function get_debounce_delay() : Int;
	
	@:overload public function set_debounce_delay(v : Int) : Void;
	
	
}
