package sun.awt.X11;
//// This file is an automatically generated file, please do not edit this file, modify the WrapperGenerator.java file instead !
extern class XkbExtensionDeviceNotifyEvent extends sun.awt.X11.XWrapperBase
{
	@:overload @:public @:static public static function getSize() : Int;
	
	@:overload @:public override public function getDataSize() : Int;
	
	@:overload @:public override public function getPData() : haxe.Int64;
	
	@:overload @:public public function new(addr : haxe.Int64) : Void;
	
	@:overload @:public public function new() : Void;
	
	@:overload @:public public function dispose() : Void;
	
	@:overload @:public public function get_type() : Int;
	
	@:overload @:public public function set_type(v : Int) : Void;
	
	@:overload @:public public function get_serial() : haxe.Int64;
	
	@:overload @:public public function set_serial(v : haxe.Int64) : Void;
	
	@:overload @:public public function get_send_event() : Bool;
	
	@:overload @:public public function set_send_event(v : Bool) : Void;
	
	@:overload @:public public function get_display() : haxe.Int64;
	
	@:overload @:public public function set_display(v : haxe.Int64) : Void;
	
	@:overload @:public public function get_time() : haxe.Int64;
	
	@:overload @:public public function set_time(v : haxe.Int64) : Void;
	
	@:overload @:public public function get_xkb_type() : Int;
	
	@:overload @:public public function set_xkb_type(v : Int) : Void;
	
	@:overload @:public public function get_device() : Int;
	
	@:overload @:public public function set_device(v : Int) : Void;
	
	@:overload @:public public function get_reason() : Int;
	
	@:overload @:public public function set_reason(v : Int) : Void;
	
	@:overload @:public public function get_supported() : Int;
	
	@:overload @:public public function set_supported(v : Int) : Void;
	
	@:overload @:public public function get_unsupported() : Int;
	
	@:overload @:public public function set_unsupported(v : Int) : Void;
	
	@:overload @:public public function get_first_btn() : Int;
	
	@:overload @:public public function set_first_btn(v : Int) : Void;
	
	@:overload @:public public function get_num_btns() : Int;
	
	@:overload @:public public function set_num_btns(v : Int) : Void;
	
	@:overload @:public public function get_leds_defined() : Int;
	
	@:overload @:public public function set_leds_defined(v : Int) : Void;
	
	@:overload @:public public function get_led_state() : Int;
	
	@:overload @:public public function set_led_state(v : Int) : Void;
	
	@:overload @:public public function get_led_class() : Int;
	
	@:overload @:public public function set_led_class(v : Int) : Void;
	
	@:overload @:public public function get_led_id() : Int;
	
	@:overload @:public public function set_led_id(v : Int) : Void;
	
	
}
