package sun.awt.X11;
//// This file is an automatically generated file, please do not edit this file, modify the WrapperGenerator.java file instead !
extern class XkbEvent extends sun.awt.X11.XWrapperBase
{
	@:overload public static function getSize() : Int;
	
	@:overload public function getDataSize() : Int;
	
	@:overload public function getPData() : haxe.Int64;
	
	@:overload public function new(addr : haxe.Int64) : Void;
	
	@:overload public function new() : Void;
	
	@:overload public function dispose() : Void;
	
	@:overload public function get_type() : Int;
	
	@:overload public function set_type(v : Int) : Void;
	
	@:overload public function get_any() : sun.awt.X11.XkbAnyEvent;
	
	@:overload public function get_new_kbd() : sun.awt.X11.XkbNewKeyboardNotifyEvent;
	
	@:overload public function get_map() : sun.awt.X11.XkbMapNotifyEvent;
	
	@:overload public function get_state() : sun.awt.X11.XkbStateNotifyEvent;
	
	@:overload public function get_ctrls() : sun.awt.X11.XkbControlsNotifyEvent;
	
	@:overload public function get_indicators() : sun.awt.X11.XkbIndicatorNotifyEvent;
	
	@:overload public function get_names() : sun.awt.X11.XkbNamesNotifyEvent;
	
	@:overload public function get_compat() : sun.awt.X11.XkbCompatMapNotifyEvent;
	
	@:overload public function get_bell() : sun.awt.X11.XkbBellNotifyEvent;
	
	@:overload public function get_message() : sun.awt.X11.XkbActionMessageEvent;
	
	@:overload public function get_accessx() : sun.awt.X11.XkbAccessXNotifyEvent;
	
	@:overload public function get_device() : sun.awt.X11.XkbExtensionDeviceNotifyEvent;
	
	@:overload public function get_core() : sun.awt.X11.XEvent;
	
	
}
