package sun.awt.X11;
//// This file is an automatically generated file, please do not edit this file, modify the WrapperGenerator.java file instead !
extern class XKeyEvent extends sun.awt.X11.XWrapperBase
{
	@:overload public static function getSize() : Int;
	
	@:overload public function getDataSize() : Int;
	
	@:overload public function getPData() : haxe.Int64;
	
	@:overload public function new(addr : haxe.Int64) : Void;
	
	@:overload public function new() : Void;
	
	@:overload public function dispose() : Void;
	
	@:overload public function get_type() : Int;
	
	@:overload public function set_type(v : Int) : Void;
	
	@:overload public function get_serial() : haxe.Int64;
	
	@:overload public function set_serial(v : haxe.Int64) : Void;
	
	@:overload public function get_send_event() : Bool;
	
	@:overload public function set_send_event(v : Bool) : Void;
	
	@:overload public function get_display() : haxe.Int64;
	
	@:overload public function set_display(v : haxe.Int64) : Void;
	
	@:overload public function get_window() : haxe.Int64;
	
	@:overload public function set_window(v : haxe.Int64) : Void;
	
	@:overload public function get_root() : haxe.Int64;
	
	@:overload public function set_root(v : haxe.Int64) : Void;
	
	@:overload public function get_subwindow() : haxe.Int64;
	
	@:overload public function set_subwindow(v : haxe.Int64) : Void;
	
	@:overload public function get_time() : haxe.Int64;
	
	@:overload public function set_time(v : haxe.Int64) : Void;
	
	@:overload public function get_x() : Int;
	
	@:overload public function set_x(v : Int) : Void;
	
	@:overload public function get_y() : Int;
	
	@:overload public function set_y(v : Int) : Void;
	
	@:overload public function get_x_root() : Int;
	
	@:overload public function set_x_root(v : Int) : Void;
	
	@:overload public function get_y_root() : Int;
	
	@:overload public function set_y_root(v : Int) : Void;
	
	@:overload public function get_state() : Int;
	
	@:overload public function set_state(v : Int) : Void;
	
	@:overload public function get_keycode() : Int;
	
	@:overload public function set_keycode(v : Int) : Void;
	
	@:overload public function get_same_screen() : Bool;
	
	@:overload public function set_same_screen(v : Bool) : Void;
	
	
}
