package sun.awt.X11;
//// This file is an automatically generated file, please do not edit this file, modify the WrapperGenerator.java file instead !
extern class XModifierKeymap extends sun.awt.X11.XWrapperBase
{
	@:overload @:public @:static public static function getSize() : Int;
	
	@:overload @:public override public function getDataSize() : Int;
	
	@:overload @:public override public function getPData() : haxe.Int64;
	
	@:overload @:public public function new(addr : haxe.Int64) : Void;
	
	@:overload @:public public function new() : Void;
	
	@:overload @:public public function dispose() : Void;
	
	@:overload @:public public function get_max_keypermod() : Int;
	
	@:overload @:public public function set_max_keypermod(v : Int) : Void;
	
	@:overload @:public public function get_modifiermap(index : Int) : haxe.Int64;
	
	@:overload @:public public function get_modifiermap() : haxe.Int64;
	
	@:overload @:public public function set_modifiermap(v : haxe.Int64) : Void;
	
	
}
