package sun.awt.X11;
//// This file is an automatically generated file, please do not edit this file, modify the WrapperGenerator.java file instead !
extern class XOMCharSetList extends sun.awt.X11.XWrapperBase
{
	@:overload public static function getSize() : Int;
	
	@:overload public function getDataSize() : Int;
	
	@:overload public function getPData() : haxe.Int64;
	
	@:overload public function new(addr : haxe.Int64) : Void;
	
	@:overload public function new() : Void;
	
	@:overload public function dispose() : Void;
	
	@:overload public function get_charset_count() : Int;
	
	@:overload public function set_charset_count(v : Int) : Void;
	
	@:overload public function get_charset_list(index : Int) : haxe.Int64;
	
	@:overload public function get_charset_list() : haxe.Int64;
	
	@:overload public function set_charset_list(v : haxe.Int64) : Void;
	
	
}
