package sun.awt.X11;
//// This file is an automatically generated file, please do not edit this file, modify the WrapperGenerator.java file instead !
extern class XOMFontInfo extends sun.awt.X11.XWrapperBase
{
	@:overload public static function getSize() : Int;
	
	@:overload override public function getDataSize() : Int;
	
	@:overload override public function getPData() : haxe.Int64;
	
	@:overload public function new(addr : haxe.Int64) : Void;
	
	@:overload public function new() : Void;
	
	@:overload public function dispose() : Void;
	
	@:overload public function get_num_font() : Int;
	
	@:overload public function set_num_font(v : Int) : Void;
	
	@:overload public function get_font_struct_list(index : Int) : haxe.Int64;
	
	@:overload public function get_font_struct_list() : haxe.Int64;
	
	@:overload public function set_font_struct_list(v : haxe.Int64) : Void;
	
	@:overload public function get_font_name_list(index : Int) : haxe.Int64;
	
	@:overload public function get_font_name_list() : haxe.Int64;
	
	@:overload public function set_font_name_list(v : haxe.Int64) : Void;
	
	
}
