package sun.awt.X11;
//// This file is an automatically generated file, please do not edit this file, modify the WrapperGenerator.java file instead !
extern class XPoint extends sun.awt.X11.XWrapperBase
{
	@:overload public static function getSize() : Int;
	
	@:overload public function getDataSize() : Int;
	
	@:overload public function getPData() : haxe.Int64;
	
	@:overload public function new(addr : haxe.Int64) : Void;
	
	@:overload public function new() : Void;
	
	@:overload public function dispose() : Void;
	
	@:overload public function get_x() : java.StdTypes.Int16;
	
	@:overload public function set_x(v : java.StdTypes.Int16) : Void;
	
	@:overload public function get_y() : java.StdTypes.Int16;
	
	@:overload public function set_y(v : java.StdTypes.Int16) : Void;
	
	
}
