package sun.awt.X11;
//// This file is an automatically generated file, please do not edit this file, modify the WrapperGenerator.java file instead !
extern class XSizeHints extends sun.awt.X11.XWrapperBase
{
	@:overload public static function getSize() : Int;
	
	@:overload override public function getDataSize() : Int;
	
	@:overload override public function getPData() : haxe.Int64;
	
	@:overload public function new(addr : haxe.Int64) : Void;
	
	@:overload public function new() : Void;
	
	@:overload public function dispose() : Void;
	
	@:overload public function get_flags() : haxe.Int64;
	
	@:overload public function set_flags(v : haxe.Int64) : Void;
	
	@:overload public function get_x() : Int;
	
	@:overload public function set_x(v : Int) : Void;
	
	@:overload public function get_y() : Int;
	
	@:overload public function set_y(v : Int) : Void;
	
	@:overload public function get_width() : Int;
	
	@:overload public function set_width(v : Int) : Void;
	
	@:overload public function get_height() : Int;
	
	@:overload public function set_height(v : Int) : Void;
	
	@:overload public function get_min_width() : Int;
	
	@:overload public function set_min_width(v : Int) : Void;
	
	@:overload public function get_min_height() : Int;
	
	@:overload public function set_min_height(v : Int) : Void;
	
	@:overload public function get_max_width() : Int;
	
	@:overload public function set_max_width(v : Int) : Void;
	
	@:overload public function get_max_height() : Int;
	
	@:overload public function set_max_height(v : Int) : Void;
	
	@:overload public function get_width_inc() : Int;
	
	@:overload public function set_width_inc(v : Int) : Void;
	
	@:overload public function get_height_inc() : Int;
	
	@:overload public function set_height_inc(v : Int) : Void;
	
	@:overload public function get_min_aspect_x() : Int;
	
	@:overload public function set_min_aspect_x(v : Int) : Void;
	
	@:overload public function get_min_aspect_y() : Int;
	
	@:overload public function set_min_aspect_y(v : Int) : Void;
	
	@:overload public function get_max_aspect_x() : Int;
	
	@:overload public function set_max_aspect_x(v : Int) : Void;
	
	@:overload public function get_max_aspect_y() : Int;
	
	@:overload public function set_max_aspect_y(v : Int) : Void;
	
	@:overload public function get_base_width() : Int;
	
	@:overload public function set_base_width(v : Int) : Void;
	
	@:overload public function get_base_height() : Int;
	
	@:overload public function set_base_height(v : Int) : Void;
	
	@:overload public function get_win_gravity() : Int;
	
	@:overload public function set_win_gravity(v : Int) : Void;
	
	
}
