package org.omg.IOP;
/**
* org/omg/IOP/Encoding.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../../src/share/classes/org/omg/PortableInterceptor/IOP.idl
* Thursday, February 21, 2013 9:14:01 AM UTC
*/
extern class Encoding implements org.omg.CORBA.portable.IDLEntity
{
	/**
	* The encoding format.
	*/
	@:public public var format : java.StdTypes.Int16;
	
	/**
	* The major version of this Encoding format.
	*/
	@:public public var major_version : java.StdTypes.Int8;
	
	/**
	* The minor version of this Encoding format.
	*/
	@:public public var minor_version : java.StdTypes.Int8;
	
	@:overload @:public public function new() : Void;
	
	@:overload @:public public function new(_format : java.StdTypes.Int16, _major_version : java.StdTypes.Int8, _minor_version : java.StdTypes.Int8) : Void;
	
	
}
