package org.omg.IOP;
/**
* org/omg/IOP/ServiceContextListHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../../src/share/classes/org/omg/PortableInterceptor/IOP.idl
* Thursday, February 21, 2013 9:14:01 AM UTC
*/
/** An array of service contexts, forming a service context list. */
extern class ServiceContextListHelper
{
	@:overload @:public @:static public static function insert(a : org.omg.CORBA.Any, that : java.NativeArray<org.omg.IOP.ServiceContext>) : Void;
	
	@:overload @:public @:static public static function extract(a : org.omg.CORBA.Any) : java.NativeArray<org.omg.IOP.ServiceContext>;
	
	@:overload @:synchronized @:public @:static public static function type() : org.omg.CORBA.TypeCode;
	
	@:overload @:public @:static public static function id() : String;
	
	@:overload @:public @:static public static function read(istream : org.omg.CORBA.portable.InputStream) : java.NativeArray<org.omg.IOP.ServiceContext>;
	
	@:overload @:public @:static public static function write(ostream : org.omg.CORBA.portable.OutputStream, value : java.NativeArray<org.omg.IOP.ServiceContext>) : Void;
	
	
}
