package org.omg.IOP;
/**
* org/omg/IOP/ServiceContextHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../../src/share/classes/org/omg/PortableInterceptor/IOP.idl
* Thursday, February 21, 2013 9:14:01 AM UTC
*/
extern class ServiceContextHolder implements org.omg.CORBA.portable.Streamable
{
	public var value : org.omg.IOP.ServiceContext;
	
	@:overload public function new() : Void;
	
	@:overload public function new(initialValue : org.omg.IOP.ServiceContext) : Void;
	
	@:overload public function _read(i : org.omg.CORBA.portable.InputStream) : Void;
	
	@:overload public function _write(o : org.omg.CORBA.portable.OutputStream) : Void;
	
	@:overload public function _type() : org.omg.CORBA.TypeCode;
	
	
}
