package org.omg.IOP;
/**
* org/omg/IOP/TaggedProfile.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../../src/share/classes/org/omg/PortableInterceptor/IOP.idl
* Thursday, February 21, 2013 9:14:01 AM UTC
*/
extern class TaggedProfile implements org.omg.CORBA.portable.IDLEntity
{
	/** The tag, represented as a profile id. */
	@:public public var tag : Int;
	
	/** The associated profile data. */
	@:public public var profile_data : java.NativeArray<java.StdTypes.Int8>;
	
	@:overload @:public public function new() : Void;
	
	@:overload @:public public function new(_tag : Int, _profile_data : java.NativeArray<java.StdTypes.Int8>) : Void;
	
	
}
