package com.sun.xml.internal.rngom.parse.compact;
/*
* Copyright (c) 2005, 2010, Oracle and/or its affiliates. All rights reserved.
* DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
*
* This code is free software; you can redistribute it and/or modify it
* under the terms of the GNU General Public License version 2 only, as
* published by the Free Software Foundation.  Oracle designates this
* particular file as subject to the "Classpath" exception as provided
* by Oracle in the LICENSE file that accompanied this code.
*
* This code is distributed in the hope that it will be useful, but WITHOUT
* ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
* FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
* version 2 for more details (a copy is included in the LICENSE file that
* accompanied this code).
*
* You should have received a copy of the GNU General Public License version
* 2 along with this work; if not, write to the Free Software Foundation,
* Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
*
* Please contact Oracle, 500 Oracle Parkway, Redwood Shores, CA 94065 USA
* or visit www.oracle.com if you need additional information or have any
* questions.
*/
/*
* Copyright (C) 2004-2011
*
* Permission is hereby granted, free of charge, to any person obtaining a copy
* of this software and associated documentation files (the "Software"), to deal
* in the Software without restriction, including without limitation the rights
* to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
* copies of the Software, and to permit persons to whom the Software is
* furnished to do so, subject to the following conditions:
*
* The above copyright notice and this permission notice shall be included in
* all copies or substantial portions of the Software.
*
* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
* IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
* FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
* AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
* LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
* OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
* THE SOFTWARE.
*/
/* Generated By:JavaCC: Do not edit this line. JavaCharStream.java Version 5.0 */
/* JavaCCOptions:STATIC=false,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
/**
* An implementation of interface CharStream, where the stream is assumed to
* contain only ASCII characters (with java-like unicode escape processing).
*/
extern class JavaCharStream
{
	/** Whether parser is static. */
	public static var staticFlag(default, null) : Bool;
	
	/** Position in buffer. */
	public var bufpos : Int;
	
	private var bufline : java.NativeArray<Int>;
	
	private var bufcolumn : java.NativeArray<Int>;
	
	private var column : Int;
	
	private var line : Int;
	
	private var prevCharIsCR : Bool;
	
	private var prevCharIsLF : Bool;
	
	private var inputStream : java.io.Reader;
	
	private var nextCharBuf : java.NativeArray<java.StdTypes.Char16>;
	
	private var buffer : java.NativeArray<java.StdTypes.Char16>;
	
	private var maxNextCharInd : Int;
	
	private var nextCharInd : Int;
	
	private var inBuf : Int;
	
	private var tabSize : Int;
	
	@:overload private function setTabSize(i : Int) : Void;
	
	@:overload private function getTabSize(i : Int) : Int;
	
	@:overload private function ExpandBuff(wrapAround : Bool) : Void;
	
	@:overload private function FillBuff() : Void;
	
	@:overload private function ReadByte() : java.StdTypes.Char16;
	
	/** @return starting character for token. */
	@:overload public function BeginToken() : java.StdTypes.Char16;
	
	@:overload private function AdjustBuffSize() : Void;
	
	@:overload private function UpdateLineColumn(c : java.StdTypes.Char16) : Void;
	
	/** Read a character. */
	@:overload public function readChar() : java.StdTypes.Char16;
	
	/**
	* @deprecated
	* @see #getEndColumn
	*/
	@:overload public function getColumn() : Int;
	
	/**
	* @deprecated
	* @see #getEndLine
	*/
	@:overload public function getLine() : Int;
	
	/** Get end column. */
	@:overload public function getEndColumn() : Int;
	
	/** Get end line. */
	@:overload public function getEndLine() : Int;
	
	/** @return column of token start */
	@:overload public function getBeginColumn() : Int;
	
	/** @return line number of token start */
	@:overload public function getBeginLine() : Int;
	
	/** Retreat. */
	@:overload public function backup(amount : Int) : Void;
	
	/** Constructor. */
	@:overload public function new(dstream : java.io.Reader, startline : Int, startcolumn : Int, buffersize : Int) : Void;
	
	/** Constructor. */
	@:overload public function new(dstream : java.io.Reader, startline : Int, startcolumn : Int) : Void;
	
	/** Constructor. */
	@:overload public function new(dstream : java.io.Reader) : Void;
	
	/** Reinitialise. */
	@:overload public function ReInit(dstream : java.io.Reader, startline : Int, startcolumn : Int, buffersize : Int) : Void;
	
	/** Reinitialise. */
	@:overload public function ReInit(dstream : java.io.Reader, startline : Int, startcolumn : Int) : Void;
	
	/** Reinitialise. */
	@:overload public function ReInit(dstream : java.io.Reader) : Void;
	
	/** Constructor. */
	@:overload public function new(dstream : java.io.InputStream, encoding : String, startline : Int, startcolumn : Int, buffersize : Int) : Void;
	
	/** Constructor. */
	@:overload public function new(dstream : java.io.InputStream, startline : Int, startcolumn : Int, buffersize : Int) : Void;
	
	/** Constructor. */
	@:overload public function new(dstream : java.io.InputStream, encoding : String, startline : Int, startcolumn : Int) : Void;
	
	/** Constructor. */
	@:overload public function new(dstream : java.io.InputStream, startline : Int, startcolumn : Int) : Void;
	
	/** Constructor. */
	@:overload public function new(dstream : java.io.InputStream, encoding : String) : Void;
	
	/** Constructor. */
	@:overload public function new(dstream : java.io.InputStream) : Void;
	
	/** Reinitialise. */
	@:overload public function ReInit(dstream : java.io.InputStream, encoding : String, startline : Int, startcolumn : Int, buffersize : Int) : Void;
	
	/** Reinitialise. */
	@:overload public function ReInit(dstream : java.io.InputStream, startline : Int, startcolumn : Int, buffersize : Int) : Void;
	
	/** Reinitialise. */
	@:overload public function ReInit(dstream : java.io.InputStream, encoding : String, startline : Int, startcolumn : Int) : Void;
	
	/** Reinitialise. */
	@:overload public function ReInit(dstream : java.io.InputStream, startline : Int, startcolumn : Int) : Void;
	
	/** Reinitialise. */
	@:overload public function ReInit(dstream : java.io.InputStream, encoding : String) : Void;
	
	/** Reinitialise. */
	@:overload public function ReInit(dstream : java.io.InputStream) : Void;
	
	/** @return token image as String */
	@:overload public function GetImage() : String;
	
	/** @return suffix */
	@:overload public function GetSuffix(len : Int) : java.NativeArray<java.StdTypes.Char16>;
	
	/** Set buffers back to null when finished. */
	@:overload public function Done() : Void;
	
	/**
	* Method to adjust line and column numbers for the start of a token.
	*/
	@:overload public function adjustBeginLineColumn(newLine : Int, newCol : Int) : Void;
	
	
}
