package org.omg.DynamicAny.DynAnyPackage;
/**
* org/omg/DynamicAny/DynAnyPackage/InvalidValueHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../../src/share/classes/org/omg/DynamicAny/DynamicAny.idl
* Thursday, February 21, 2013 9:14:03 AM UTC
*/
extern class InvalidValueHelper
{
	@:overload public static function insert(a : org.omg.CORBA.Any, that : org.omg.DynamicAny.DynAnyPackage.InvalidValue) : Void;
	
	@:overload public static function extract(a : org.omg.CORBA.Any) : org.omg.DynamicAny.DynAnyPackage.InvalidValue;
	
	@:overload @:synchronized public static function type() : org.omg.CORBA.TypeCode;
	
	@:overload public static function id() : String;
	
	@:overload public static function read(istream : org.omg.CORBA.portable.InputStream) : org.omg.DynamicAny.DynAnyPackage.InvalidValue;
	
	@:overload public static function write(ostream : org.omg.CORBA.portable.OutputStream, value : org.omg.DynamicAny.DynAnyPackage.InvalidValue) : Void;
	
	
}
