package org.omg.PortableServer.CurrentPackage;
/**
* org/omg/PortableServer/CurrentPackage/NoContextHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../../src/share/classes/org/omg/PortableServer/poa.idl
* Thursday, February 21, 2013 9:14:01 AM UTC
*/
extern class NoContextHelper
{
	@:overload public static function insert(a : org.omg.CORBA.Any, that : org.omg.PortableServer.CurrentPackage.NoContext) : Void;
	
	@:overload public static function extract(a : org.omg.CORBA.Any) : org.omg.PortableServer.CurrentPackage.NoContext;
	
	@:overload @:synchronized public static function type() : org.omg.CORBA.TypeCode;
	
	@:overload public static function id() : String;
	
	@:overload public static function read(istream : org.omg.CORBA.portable.InputStream) : org.omg.PortableServer.CurrentPackage.NoContext;
	
	@:overload public static function write(ostream : org.omg.CORBA.portable.OutputStream, value : org.omg.PortableServer.CurrentPackage.NoContext) : Void;
	
	
}
