package org.omg.PortableServer;
/**
* org/omg/PortableServer/IdUniquenessPolicyValue.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../../src/share/classes/org/omg/PortableServer/poa.idl
* Thursday, February 21, 2013 9:14:01 AM UTC
*/
/**
	 * IdUniquenessPolicyValue can have the following values.
	 * UNIQUE_ID - Servants activated with that POA support 
	 * exactly one Object Id.  MULTIPLE_ID - a servant 
	 * activated with that POA may support one or more 
	 * Object Ids.
	 */
extern class IdUniquenessPolicyValue implements org.omg.CORBA.portable.IDLEntity
{
	public static var _UNIQUE_ID(default, null) : Int;
	
	public static var UNIQUE_ID(default, null) : org.omg.PortableServer.IdUniquenessPolicyValue;
	
	public static var _MULTIPLE_ID(default, null) : Int;
	
	public static var MULTIPLE_ID(default, null) : org.omg.PortableServer.IdUniquenessPolicyValue;
	
	@:overload public function value() : Int;
	
	@:overload public static function from_int(value : Int) : org.omg.PortableServer.IdUniquenessPolicyValue;
	
	@:overload private function new(value : Int) : Void;
	
	
}
