package org.omg.PortableServer;
/**
* org/omg/PortableServer/IdUniquenessPolicyOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../../src/share/classes/org/omg/PortableServer/poa.idl
* Thursday, February 21, 2013 9:14:01 AM UTC
*/
/**
	 * The IdUniquenessPolicy specifies whether the servants 
	 * activated in the created POA must have unique object i
	 * identities. The default is UNIQUE_ID.
	 */
extern interface IdUniquenessPolicyOperations extends org.omg.CORBA.PolicyOperations
{
	/**
		 * specifies the policy value
		 */
	@:overload public function value() : org.omg.PortableServer.IdUniquenessPolicyValue;
	
	
}
