package org.omg.PortableServer;
/**
* org/omg/PortableServer/LifespanPolicyOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../../src/share/classes/org/omg/PortableServer/poa.idl
* Thursday, February 21, 2013 9:14:01 AM UTC
*/
/**
	 * The LifespanPolicy specifies the lifespan of the 
	 * objects implemented in the created POA. The default 
	 * is TRANSIENT.
	 */
extern interface LifespanPolicyOperations extends org.omg.CORBA.PolicyOperations
{
	/**
		 * specifies the policy value
		 */
	@:overload public function value() : org.omg.PortableServer.LifespanPolicyValue;
	
	
}
