package org.omg.PortableServer;
/**
* org/omg/PortableServer/RequestProcessingPolicyValue.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../../src/share/classes/org/omg/PortableServer/poa.idl
* Thursday, February 21, 2013 9:14:01 AM UTC
*/
/**
	 * The RequestProcessingPolicyValue can have the following
	 * values.  USE_ACTIVE_OBJECT_MAP_ONLY - If the Object Id 
	 * is not found in the Active Object Map, 
	 * an OBJECT_NOT_EXIST exception is returned to the 
	 * client. The RETAIN policy is also required.
	 * USE_DEFAULT_SERVANT - If the Object Id is not found in 
	 * the Active Object Map or the NON_RETAIN policy is 
	 * present, and a default servant has been registered 
	 * with the POA using the set_servant operation, 
	 * the request is dispatched to the default servant. 
	 * USE_SERVANT_MANAGER - If the Object Id is not found 
	 * in the Active Object Map or the NON_RETAIN policy 
	 * is present, and a servant manager has been registered 
	 * with the POA using the set_servant_manager operation, 
	 * the servant manager is given the opportunity to 
	 * locate a servant or raise an exception. 
	 */
extern class RequestProcessingPolicyValue implements org.omg.CORBA.portable.IDLEntity
{
	public static var _USE_ACTIVE_OBJECT_MAP_ONLY(default, null) : Int;
	
	public static var USE_ACTIVE_OBJECT_MAP_ONLY(default, null) : org.omg.PortableServer.RequestProcessingPolicyValue;
	
	public static var _USE_DEFAULT_SERVANT(default, null) : Int;
	
	public static var USE_DEFAULT_SERVANT(default, null) : org.omg.PortableServer.RequestProcessingPolicyValue;
	
	public static var _USE_SERVANT_MANAGER(default, null) : Int;
	
	public static var USE_SERVANT_MANAGER(default, null) : org.omg.PortableServer.RequestProcessingPolicyValue;
	
	@:overload public function value() : Int;
	
	@:overload public static function from_int(value : Int) : org.omg.PortableServer.RequestProcessingPolicyValue;
	
	@:overload private function new(value : Int) : Void;
	
	
}
