package org.omg.PortableServer;
/**
* org/omg/PortableServer/ServantActivator.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../../src/share/classes/org/omg/PortableServer/poa.idl
* Thursday, February 21, 2013 9:14:01 AM UTC
*/
/**
	 * When the POA has the RETAIN policy it uses servant 
	 * managers that are ServantActivators. 
	 */
extern interface ServantActivator extends org.omg.PortableServer.ServantActivatorOperations extends org.omg.PortableServer.ServantManager extends org.omg.CORBA.portable.IDLEntity
{
	
}
