package org.omg.PortableServer;
/**
* org/omg/PortableServer/ServantRetentionPolicy.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../../src/share/classes/org/omg/PortableServer/poa.idl
* Thursday, February 21, 2013 9:14:01 AM UTC
*/
/**
	 * This policy specifies whether the created POA retains 
	 * active servants in an Active Object Map. 
	 */
extern interface ServantRetentionPolicy extends org.omg.PortableServer.ServantRetentionPolicyOperations extends org.omg.CORBA.Policy extends org.omg.CORBA.portable.IDLEntity
{
	
}
