package com.sun.corba.se.spi.activation;
/**
* com/sun/corba/se/spi/activation/LocatorOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../../src/share/classes/com/sun/corba/se/spi/activation/activation.idl
* Thursday, February 21, 2013 9:14:13 AM UTC
*/
extern interface LocatorOperations
{
	@:overload public function locateServer(serverId : Int, endPoint : String) : com.sun.corba.se.spi.activation.LocatorPackage.ServerLocation;
	
	@:overload public function locateServerForORB(serverId : Int, orbId : String) : com.sun.corba.se.spi.activation.LocatorPackage.ServerLocationPerORB;
	
	@:overload public function getEndpoint(endPointType : String) : Int;
	
	@:overload public function getServerPortForType(location : com.sun.corba.se.spi.activation.LocatorPackage.ServerLocationPerORB, endPointType : String) : Int;
	
	
}
