package com.sun.corba.se.spi.activation;
/**
* com/sun/corba/se/spi/activation/ServerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../../src/share/classes/com/sun/corba/se/spi/activation/activation.idl
* Thursday, February 21, 2013 9:14:13 AM UTC
*/
/** Server callback API, passed to Activator in active method.
*/
extern interface ServerOperations
{
	/** Shutdown this server.  Returns after orb.shutdown() completes.
		*/
	@:overload public function shutdown() : Void;
	
	/** Install the server.  Returns after the install hook completes
		* execution in the server.
		*/
	@:overload public function install() : Void;
	
	/** Uninstall the server.  Returns after the uninstall hook
		* completes execution.
		*/
	@:overload public function uninstall() : Void;
	
	
}
