package com.sun.corba.se.spi.activation;
/**
* com/sun/corba/se/spi/activation/TCPPortHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../../src/share/classes/com/sun/corba/se/spi/activation/activation.idl
* Thursday, February 21, 2013 9:14:13 AM UTC
*/
extern class TCPPortHelper
{
	@:overload public static function insert(a : org.omg.CORBA.Any, that : Int) : Void;
	
	@:overload public static function extract(a : org.omg.CORBA.Any) : Int;
	
	@:overload @:synchronized public static function type() : org.omg.CORBA.TypeCode;
	
	@:overload public static function id() : String;
	
	@:overload public static function read(istream : org.omg.CORBA.portable.InputStream) : Int;
	
	@:overload public static function write(ostream : org.omg.CORBA.portable.OutputStream, value : Int) : Void;
	
	
}
