package org.omg.DynamicAny;
/**
* org/omg/DynamicAny/DynFixedHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../../src/share/classes/org/omg/DynamicAny/DynamicAny.idl
* Thursday, February 21, 2013 9:14:03 AM UTC
*/
/**
* DynFixed objects support the manipulation of IDL fixed values.
* Because IDL does not have a generic type that can represent fixed types with arbitrary
* number of digits and arbitrary scale, the operations use the IDL string type.
*/
extern class DynFixedHelper
{
	@:overload public static function insert(a : org.omg.CORBA.Any, that : org.omg.DynamicAny.DynFixed) : Void;
	
	@:overload public static function extract(a : org.omg.CORBA.Any) : org.omg.DynamicAny.DynFixed;
	
	@:overload @:synchronized public static function type() : org.omg.CORBA.TypeCode;
	
	@:overload public static function id() : String;
	
	@:overload public static function read(istream : org.omg.CORBA.portable.InputStream) : org.omg.DynamicAny.DynFixed;
	
	@:overload public static function write(ostream : org.omg.CORBA.portable.OutputStream, value : org.omg.DynamicAny.DynFixed) : Void;
	
	@:overload public static function narrow(obj : org.omg.CORBA.Object) : org.omg.DynamicAny.DynFixed;
	
	@:overload public static function unchecked_narrow(obj : org.omg.CORBA.Object) : org.omg.DynamicAny.DynFixed;
	
	
}
