package org.omg.DynamicAny;
/**
* org/omg/DynamicAny/DynSequenceHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../../src/share/classes/org/omg/DynamicAny/DynamicAny.idl
* Thursday, February 21, 2013 9:14:03 AM UTC
*/
/**
* DynSequence objects support the manipulation of IDL sequences.
*/
extern class DynSequenceHelper
{
	@:overload @:public @:static public static function insert(a : org.omg.CORBA.Any, that : org.omg.DynamicAny.DynSequence) : Void;
	
	@:overload @:public @:static public static function extract(a : org.omg.CORBA.Any) : org.omg.DynamicAny.DynSequence;
	
	@:overload @:synchronized @:public @:static public static function type() : org.omg.CORBA.TypeCode;
	
	@:overload @:public @:static public static function id() : String;
	
	@:overload @:public @:static public static function read(istream : org.omg.CORBA.portable.InputStream) : org.omg.DynamicAny.DynSequence;
	
	@:overload @:public @:static public static function write(ostream : org.omg.CORBA.portable.OutputStream, value : org.omg.DynamicAny.DynSequence) : Void;
	
	@:overload @:public @:static public static function narrow(obj : org.omg.CORBA.Object) : org.omg.DynamicAny.DynSequence;
	
	@:overload @:public @:static public static function unchecked_narrow(obj : org.omg.CORBA.Object) : org.omg.DynamicAny.DynSequence;
	
	
}
