package org.omg.DynamicAny;
/**
* org/omg/DynamicAny/DynValueCommon.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../../src/share/classes/org/omg/DynamicAny/DynamicAny.idl
* Thursday, February 21, 2013 9:14:03 AM UTC
*/
/**
* DynValueCommon provides operations supported by both the DynValue and DynValueBox interfaces.
*/
extern interface DynValueCommon extends org.omg.DynamicAny.DynValueCommonOperations extends org.omg.DynamicAny.DynAny extends org.omg.CORBA.portable.IDLEntity
{
	
}
