package javax.management.remote.rmi;
//// Stub class generated by rmic, do not edit.
//// Contents subject to change without notice.
extern class RMIServerImpl_Stub extends java.rmi.server.RemoteStub implements javax.management.remote.rmi.RMIServer
{
	@:overload public function new(ref : java.rmi.server.RemoteRef) : Void;
	
	@:overload public function getVersion() : String;
	
	@:overload public function newClient($param_Object_1 : Dynamic) : javax.management.remote.rmi.RMIConnection;
	
	
}
