package org.omg.CosNaming.NamingContextExtPackage;
/**
* org/omg/CosNaming/NamingContextExtPackage/InvalidAddress.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../../src/share/classes/org/omg/CosNaming/nameservice.idl
* Thursday, February 21, 2013 9:14:02 AM UTC
*/
extern class InvalidAddress extends org.omg.CORBA.UserException
{
	@:overload @:public public function new() : Void;
	
	@:overload @:public public function new($reason : String) : Void;
	
	
}
