package org.omg.PortableInterceptor;
/**
* org/omg/PortableInterceptor/AdapterStateHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../../src/share/classes/org/omg/PortableInterceptor/Interceptors.idl
* Thursday, February 21, 2013 9:14:02 AM UTC
*/
/** Type of object adapter state.  State changes are reported either to
* the object adapter or to the adapter manager.
*/
extern class AdapterStateHelper
{
	@:overload @:public @:static public static function insert(a : org.omg.CORBA.Any, that : java.StdTypes.Int16) : Void;
	
	@:overload @:public @:static public static function extract(a : org.omg.CORBA.Any) : java.StdTypes.Int16;
	
	@:overload @:synchronized @:public @:static public static function type() : org.omg.CORBA.TypeCode;
	
	@:overload @:public @:static public static function id() : String;
	
	@:overload @:public @:static public static function read(istream : org.omg.CORBA.portable.InputStream) : java.StdTypes.Int16;
	
	@:overload @:public @:static public static function write(ostream : org.omg.CORBA.portable.OutputStream, value : java.StdTypes.Int16) : Void;
	
	
}
