package org.omg.PortableInterceptor;
/**
* org/omg/PortableInterceptor/Interceptor.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../../src/share/classes/org/omg/PortableInterceptor/Interceptors.idl
* Thursday, February 21, 2013 9:14:02 AM UTC
*/
/**
* All Portable Interceptors implement Interceptor.
*/
extern interface Interceptor extends org.omg.PortableInterceptor.InterceptorOperations extends org.omg.CORBA.Object extends org.omg.CORBA.portable.IDLEntity
{
	
}
