package org.omg.PortableInterceptor;
/**
* org/omg/PortableInterceptor/IORInterceptor_3_0.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../../src/share/classes/org/omg/PortableInterceptor/Interceptors.idl
* Thursday, February 21, 2013 9:14:02 AM UTC
*/
extern interface IORInterceptor_3_0 extends org.omg.PortableInterceptor.IORInterceptor_3_0Operations extends org.omg.PortableInterceptor.IORInterceptor extends org.omg.CORBA.portable.IDLEntity
{
	
}
