package org.omg.PortableInterceptor;
/**
* org/omg/PortableInterceptor/ObjectReferenceFactory.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../../src/share/classes/org/omg/PortableInterceptor/Interceptors.idl
* Thursday, February 21, 2013 9:14:02 AM UTC
*/
/** The object reference factory.  This provides the capability of
* creating an object reference.
*/
extern interface ObjectReferenceFactory extends org.omg.CORBA.portable.ValueBase
{
	/** make_object creates a CORBA object reference according
	* to the data in this template, with the given repository ID and
	* object ID.
	*/
	@:overload @:public @:abstract public function make_object(repositoryId : String, object_id : java.NativeArray<java.StdTypes.Int8>) : org.omg.CORBA.Object;
	
	
}
